name: Variables
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            USERNAME: ${{ vars.USERNAME }}
        steps:
            - run: echo "${{ github.event_name }}"
            - run: echo "${{ github.actor }}"
            - run: echo "${{ github.repository }}"
            - run: echo "${{ github.sha }}"
            - run: echo "${{ github.workflow }}"
            - run: echo "${{ github.run_id }}"
            - run: echo "${{ github.run_number }}"
            - run: echo "${{ github.event }}"
            - run: echo "${USERNAME}"